kind: Service
apiVersion: v1
metadata:
  name: freeyeti-ghstat-api
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: freeyeti-ghstat-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http